# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #   __________              __  .__       .__           ________
 #    \______   \\____________/  |_|__| ____ |  |   ____  /  _____/ __ __  ____
# #   |     ___/  _ \\_  __ \\   __\\  |/ ___\\|  | _/ __ \\/   \\  ___|  |  \/    \\
 #    |    |  (  <_> )  | \/|  | |  \\  \\___|  |_\\  ___/\\    \\_\\  \\  |  /   |  \\
# #   |____|   \\____/|__|   |__| |__|\\___  >____/\\___  >\\______  /____/|___|  /
 #                                       \\/          \\/        \\/           \\/
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

portal:
  # Maximum distance (in blocks) a target block can be traced for portal placement.
  max-target-distance: 128
  # Maximum distance (in blocks) between the player and the targeted portal location.
  max-player-distance: 100
  # Maximum distance (in blocks) used when determining the face of the targeted block.
  max-block-trace: 100
