name: PorticleGun
version: v1.2.2-SNAPSHOT
main: eu.nurkert.porticlegun.PorticleGun
api-version: 1.19
authors: [ nurkert ]

commands:
  porticlegun:
    description: Manage or obtain a PorticleGun
    usage: /<command> [removeportal [linked]|list|remove <id>|clearplayer <player>|reload]
    permission: porticlegun.command
    tab-completer: eu.nurkert.porticlegun.commands.PorticleGunCommand

permissions:
  porticlegun.command:
    description: Allows using /porticlegun to obtain a gun
    default: true
  porticlegun.admin:
    description: Allows administrative PorticleGun management commands
    default: op
