name: PorticleGun
version: v1.2.2-SNAPSHOT
main: eu.nurkert.porticlegun.PorticleGun
api-version: 1.19
authors: [ nurkert ]

commands:
  porticlegun:
    description: Get a PorticleGun
    usage: /porticlegun
    permission: porticlegun.command