name: PorticleGun
version: v1.2.2-SNAPSHOT
main: eu.nurkert.porticlegun.PorticleGun
api-version: 1.19
authors: [ nurkert ]

commands:
  porticlegun:
    description: Get a PorticleGun or manage the plugin
    usage: /porticlegun [list|remove <id>|clearplayer <name>|reload]
    permission: porticlegun.command

permissions:
  porticlegun.command:
    description: Allows using the /porticlegun command to obtain a portal gun.
    default: op
  porticlegun.admin:
    description: Allows managing stored portals, clearing players and reloading the plugin.
    default: op
